# This file was generated by GoReleaser. DO NOT EDIT.
class Square < Formula
  desc ""
  homepage ""
  version "0.0.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nickrobinson/square-cli/releases/download/v0.0.9/square_0.0.9_Darwin_x86_64.tar.gz"
    sha256 "f5e755d092d14835dc9c4b72a9d9fbc557633038c69d567f42b8bf0481353133"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/nickrobinson/square-cli/releases/download/v0.0.9/square_0.0.9_Linux_x86_64.tar.gz"
      sha256 "af69b2d5795ea259d573052f99421f321f981c91933354f099dfdb40c6652c1e"
    end
  end

  def install
    bin.install "square"
  end
end
