# This file was generated by GoReleaser. DO NOT EDIT.
class Square < Formula
  desc ""
  homepage ""
  version "0.0.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nickrobinson/square-cli/releases/download/v0.0.7/square_0.0.7_Darwin_x86_64.tar.gz"
    sha256 "41cc93caa0dabb60fa3d4cef73007218a901052530c12c026b9b8c8c03b96fa3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/nickrobinson/square-cli/releases/download/v0.0.7/square_0.0.7_Linux_x86_64.tar.gz"
      sha256 "dde4fb7612488e8e77bb61476ce93d9332a1c0ded4472739d9479d14bd6ce4be"
    end
  end

  def install
    bin.install "square"
  end
end
