# This file was generated by GoReleaser. DO NOT EDIT.
class Square < Formula
  desc ""
  homepage ""
  version "0.0.8"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nickrobinson/square-cli/releases/download/v0.0.8/square_0.0.8_Darwin_x86_64.tar.gz"
    sha256 "b7faaac1b5109c10ce04927b2d70aee1900a93a4e8ff149ee8bfa400838a7049"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/nickrobinson/square-cli/releases/download/v0.0.8/square_0.0.8_Linux_x86_64.tar.gz"
      sha256 "7191ae3d67ee3aea26a2d3b8f54e272b543a220b465e282d83e6cba62e167a0d"
    end
  end

  def install
    bin.install "square"
  end
end
